import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";
import theme from "../theme/themeConfig";
import AppSideLayout from "./components/AppSideLayout";
import { UserRole } from "./config/menuItems";

// Mock function: Replace this with your actual Auth logic (NextAuth, Clerk, etc.)
async function getCurrentUserRole(): Promise<UserRole> {
  // Example: const session = await getServerSession();
  // return session?.user?.role || 'user';

  return "user";
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const role = await getCurrentUserRole();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AntdRegistry>
          <ConfigProvider theme={theme}>
            <AppSideLayout userRole={role}>{children}</AppSideLayout>
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
